Application_Django/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='Show'),
    path('Delete/<int:id>/', Delete, name='Delete'),
    path('Update/<str:id>', Update, name='Update')
]

Project_CRUD/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Application_Django.urls'))
]

Application_Django/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    Gender_choices = [
        ("Nam", "Nam"),
        ("Nữ", "Nữ"),
        ("Khác", "Khác")
    ]
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(choices=Gender_choices, max_length=10)

Application_Django/views.py
from django.shortcuts import render, redirect
from .models import Student

# Create your views here.
def index(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        age = request.POST.get('age')
        gender = request.POST.get('gender')
        print(name, age, gender)
        
        if name and age and gender:
            save = Student(name=name, age=age, gender=gender)
            save.save()
            print(name, age, gender)
            return redirect('/') 
    students = Student.objects.all()
    return render(request, 'index.html', {'students': students})

def Delete(request, id):
    if request.method == 'POST':
        id_delete = Student.objects.get(pk=id)
        id_delete.delete()
        return redirect('/')

def Update(request, id):
    if request.method == "POST":
        edit_name = request.POST.get('edit_name')
        edit_age = request.POST.get('edit_age')
        edit_gender = request.POST.get('edit_gender')
        if edit_name and edit_age and edit_gender:
            save = Student(id=id, name=edit_name, age=edit_age, gender=edit_gender)
            save.save()
            return redirect('/')
    return render(request, 'index.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD - Database</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js" integrity="sha512-uKQ39gEGiyUJl4AI6L+ekBdGKpGw4xJ55+xyJG7YFlJokPNYegn9KwQ3P8A7aFQAUtUsAQHep+d/lrGqrbPIDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-danger">Django Project CRUD</h2>
        {% block main %}{% endblock main %}
    </div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block main %}
    <div class="row">
        <div class="col-sm-4">
            <h4 class="text-center alert alert-info">Thêm thông tin</h4>
            <form action="" method="post">
                {% csrf_token %}
                <p>
                    <label for="id_name">Name:</label>
                    <input type="text" name="name" class="form-control" maxlength="100" id="id_name" required>
                </p>
                <p>
                    <label for="id_age">Age:</label>
                    <input type="text" name="age" class="form-control" id="id_age" required>
                </p>
                <p>
                    <label for="id_gender">Gender:</label>
                    <select name="gender" class="form-control" id="id_gender" required>
                    <option value="" selected="">---------</option>
                    <option value="Nam">Nam</option>
                    <option value="Nữ">Nữ</option>
                    <option value="Khác">Khác</option>
                </select>
                </p>
                <input type="submit" value="Add" class="btn btn-success">
            </form>
        </div>

        <div class="col-sm-8">
            <h4 class="text-center alert alert-info">Thông tin sinh viên</h4>
            <table id="table_id" class="table table-hover" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Age</th>
                        <th>Gender</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for show in students %}
                    <tr>
                        <th>{{forloop.counter}}</th>
                        <td>{{show.name}}</td>
                        <td>{{show.age}}</td>
                        <td>{{show.gender}}</td>
                        <td>
                            <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#edit-{{show.id}}">
                                <i class="fa-regular fa-pen-to-square"></i>
                            </button>
                            <form action="{% url 'Delete' show.id %}" method="post" class='d-inline'>
                                {% csrf_token %}
                                <button class="btn btn-danger btn-sm" type='submit'>
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    {% for i in students %}
        <form action="/Update/{{i.id}}" method="post">
            <div class="modal fade" id="edit-{{i.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                {% csrf_token %}
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Chỉnh sửa thông tin</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <label>Name</label>
                            <input name="edit_name" value="{{i.name}}" type="text" class="form-control" required>
                            <label>Age</label>
                            <input name="edit_age" value="{{i.age}}" type="text" class="form-control" required>
                            <label>Gender</label>
                            <input name="edit_gender" value="{{i.gender}}" type="text" class="form-control" required>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    {% endfor %}

    <script>
        new DataTable('#table_id');
    </script>
    
{% endblock main %}